#!/bin/sh
command=compiz-manager

userbindkey=$HOME/.xbindkeysrc

if [ -f "$userbindkey" ]; then
    xbindkeys
fi

userresources=$HOME/.Xresources

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

#/usr/local/bin/SwitchLAltSuper

#xmodmap $HOME/.xmodmap

tint2 &
fcitx-autostart &
/usr/libexec/polkit-gnome-authentication-agent-1 &

exec $command

