#!/bin/sh
command=compiz-manager

# /usr/local/bin/SwitchLAltSuper

userbindkey=$HOME/.xbindkeysrc

if [ -f "$userbindkey" ]; then
    xbindkeys
fi

userresources=$HOME/.Xresources

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi


tint2 &
fcitx-autostart &
/usr/libexec/lxpolkit &


exec $command

