#!/bin/sh
command=compiz-manager

userbindkey=$HOME/.xbindkeysrc

if [ -f "$userbindkey" ]; then
    xbindkeys
fi

userresources=$HOME/.Xresources

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

usermodmap=$HOME/.xmodmap

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


tint2 &
fcitx-autostart &
/usr/libexec/lxpolkit &


exec $command

