alias ga='git add -A .'
alias gacp='ga;git commit --fixup HEAD;git push'
alias gb='git checkout'
alias gcx='git clean -xfd'
alias gd='git diff'
alias gfp='git fetch -p --all'
alias gfr='gfp;gm;git reset --hard origin/master'
alias gl='git log --graph --full-history --all --pretty=format:"%h%x09%d%x20%s"'
alias gm='gb master'
alias gmm='git commit --amend --no-edit'
alias gmt='git commit -m "tmp"'
alias gr='git reflog'
alias grc='grh; gcx'
alias grh='git reset --hard'
alias gs='git status'
alias gv='gitk --all'
