export ZSH=$HOME/git/oh-my-zsh
DISABLE_AUTO_UPDATE="true"

ZSH_TMUX_AUTOSTART="true"
#ZSH_TMUX_AUTOSTART_ONCE="true"
ZSH_TMUX_AUTOQUIT="false"
plugins=(tmux archlinux)

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

ZSH_CUSTOM=$HOME/.omz
source $ZSH/oh-my-zsh.sh
